export const createUsersSlice = (set) => ({
  users: [
    { id: 1,
      name: "John Doe",
      email: "john.doe@email.com",
      address: "Kopo, Bandung City",
      birthdate: "1990-01-01",
      currentColleague: "Jane Smith",
      hobbies: ["Reading", "Coding", "Chess"],
      photo: "https://via.placeholder.com/150"
    },
    { id: 2, name: 'Jane Doe', 
      email: 'jane.doe@email.id',
      addres: 'Kopo, Bandung City',
      birthdate: '1991-01-01',
      currentColleague: 'John Doe',
      hobbies: ['Reading', 'Eating', 'Fishing'],
      photo: 'https://via.placeholder.com/150'
    },
    { id: 3, name: 'Jim Doe',
      email: 'jim.doe@email.id',
      addres: 'Kopo, Bandung City',
      birthdate: '1992-01-01',
      currentColleague: 'Jane Doe',
      hobbies: ['Playing', 'Hiking', 'Helping'],
    },
    { id: 4, name: 'Jack Doe', 
      email: 'jack.doe@email.id',
      addres: 'Kopo, Bandung City',
      birthdate: '1993-01-01',
      currentColleague: 'Jim Doe',
      hobbies: ['Racing', 'Editing', 'Cooking'],
    },
    { id: 5, name: 'Jill Doe',
      email: 'jill.doe@email.id',
      addres: 'Kopo, Bandung City',
      birthdate: '1994-01-01',
      currentColleague: 'Jack Doe',
      hobbies: ['Writing', 'Painting', 'Photography'],
    },
    { id: 6, name: 'Joe Doe',
      email: 'joe.doe@email.id',
      addres: 'Kopo, Bandung City',
      birthdate: '1995-01-01',
      currentColleague: 'Jill Doe',
      hobbies: ['Singing', 'Dancing', 'Playing'],
    },
    { id: 7, name: 'Judy Doe',
      email: 'judy.doe@email.id',
      address: 'Kopo, Bandung City',
      birthdate: '1996-01-01',
      currentColleague: 'Joe Doe',
      hobbies: ['Gardening', 'Yoga', 'Meditation'],
    },
    { id: 8, name: 'Jake Doe',
      email: 'jake.doe@email.id',
      addres: 'Kopo, Bandung City',
      birthdate: '1997-01-01',
      currentColleague: 'Judy Doe',
      hobbies: ['Cycling', 'Swimming', 'Running'],
    },
    { id: 9, name: 'Jessie Doe',
      email: 'jessie.doe@email.id',
      addres: 'Kopo, Bandung City',
      birthdate: '1998-01-01',
      currentColleague: 'Jake Doe',
      hobbies: ['Painting', 'Sculpture', 'Photography'],
    },
    { id: 10, name: 'Jordan Doe',
      email: 'jordan.doe@email.id',
      address: 'Kopo, Bandung City',
      birthdate: '1999-01-01',
      currentColleague: 'Jessie Doe',
      hobbies: ['Playing', 'Hiking', 'Helping'],
    },
  ],
  setUsers: (users) => set({ users }),
})
